name: Deploy to Dev Environments

on:
  workflow_dispatch:
    # Input variables for pipelines
    inputs:
      targetServer: 
        type: choice
        description: Specifies the deployment target environment/server
        options: 
          - DEVM
          - INTP
          - INT
      version:
        description: "Specify the version to deploy"
        default: "2.60.0-SNAPSHOT"
      bypassCodeFreeze:
        type: boolean
        description: "If enabled, the code-freeze check will be bypassed"
        default: true
    
jobs:
  
    send_teams_notifiation_start:
      name: Send Teams Notification - Start
      runs-on: ubuntu-latest
      steps:
        - name: Sending message
          uses: skitionek/notify-microsoft-teams@master
          if: always()
          with:
            webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
            raw: >-
              {
                "@type": "MessageCard",
                "@context": "http://schema.org/extensions",
                "title": "Deploying to ${{ github.event.inputs.targetServer }}, pipeline is starting"
              }
      
    fetch_artifacts:
        name: Fetch Artifacts
        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v3
         
          - name: with curl
            run: curl -u user:password -L -X GET 'https://DAIMLA_NEXUS/service/rest/v1/search/assets/download?sort=version&repository=MY-REPO&group=MY_GROUP&name=MY_ARTIFACT_NAME&maven.baseVersion=0.1-SNAPSHOT' --output some.file
    
    deploy_aem:
      name: Deploy artifacts to AEM
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::123456789100:role/my-github-actions-role
            aws-region: us-east-2
        - name: disable awsAlarmOperation 
          run: echo "In progress"
          
        - name: awsTargetGroupOperation AWS from Loadbalancer
          run: echo "In progress" 
        
        - name: awsCreateEc2Snapshot creating snapshot
          run: echo "In progress" 
    
    deploy_aem_devm_author: # It will be template, can be reused to other environments 
      name: Deploying DEVM Author
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: echo "In progress"
          
    deploy_aem_devm_publish: # It will be template, can be reused to other environments 
      name: Deploying DEVM Publish
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: echo "In progress"
          
    post_deployment_actions_on_author:
      name: Run post deployment actions on Author
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: echo "In progress"
           
    trigger_smoke_tests_devm: # It will be template, can be reused to other environments 
      name: Run smoke tests
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: echo "In progress"
          
    update_jira_information:  
      name: Update to JIRA APWIDE
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: curl -u ${{ secrets.JIRA_USERNAME }}:${{ secrets.JIRA_PASSWORD }} --location --request PUT https://jira.mercedes-benz.io/rest/apwide/tem/1.1/deployment?application=VANS&category=Dev&time=1678458520108 
    
    execute_seamless_releases:
      name: Execute Seamless Release Update
      runs-on: ubuntu-latest
      steps:
        - name: deploy
          run: echo "In progress" # "/system/console/jmx/com.daimler.vans.cq.models.seamless.impl:type=SeamlessReleaseConfigUpdateMBeanImpl/op/executeReleaseUpdate/"
    
    send_teams_notifiation_end:
        name: Send Teams Notification - End
        runs-on: ubuntu-latest
        steps:
          - name: Sending message
            uses: skitionek/notify-microsoft-teams@master
            if: always()
            with:
              webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
              raw: >-
                {
                  "@type": "MessageCard",
                  "@context": "http://schema.org/extensions",
                  "title": "Deploying to ${{ github.event.inputs.targetServer }}, pipeline is finished"
                }
            
